version: 0.0
os: linux
# this is what happens during the install event
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root 
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/backup_file
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/check_service
      timeout: 300
      runas: root 

