#!/bin/bash
set -e 

public_ip=$(curl http://169.254.169.254/latest/meta-data/public-ipv4)
host_name=$(curl http://169.254.169.254/latest/meta-data/local-hostname
instance_ide=$(curl http://169.254.169.254/latest/meta-data/instanceId e

INDEX_FILE=/var/www/html/index.html
INDEX_FILE=/var/www/html/index.html

sed -i '' 's/<\/body>//g' $TARGET_FILE 
sed -i '' 's/<\/html>//g' $TARGET_FILE 

if [ ! $(grep 'APPLICATION_NAME' $TARGET_FILE) ]; then

    echo "<div class='codedeploy'>">>$TARGET_FILE
    echo '<hr/>'>>$TARGET_FILE 
    echo "<h2>CodeDeploy Details</h2>">>$TARGET_FILE
    echo "<p>">>$TARGET_FILE
    echo "APPLICATION_NAME:$APPLICATION_NAME<br>">>$TARGET_FILE
    echo "DEPLOYMENT_ID:$DEPLOYMENT_ID<br>">>$TARGET_FILE
    echo "DEPLOYMENT_GROUP_NAME:$DEPLOYMENT_GROUP_NAME<br>">>$TARGET_FILE
    echo "DEPLOYMENT_GROUP_ID:$DEPLOYMENT_GROUP_ID<br>">>$TARGET_FILE
fi

echo "LIFECYCLE_EVENT:$LIFECYCLE_EVENT<br>">>$TARGET_FILE
    echo "</div>">>$TARGET_FILE
echo "</body>">>$TARGET_FILE
echo "</html>">>$TARGET_FILE
