#!/bin/bash
set -e 

INDEX_FILE=/var/www/html/index.html

if [ -f $INDEX_FILE ]; then
    TARGET_FILE=$INDEX_FILE 
else
    TARGET_FILE=../index.html
fi 

# TARGET_FILE=index.html
TARGET_BKUP=index.bkup
cp "$TARGET_FILE" "$TARGET_BKUP"

echo TARGET_FILE IS $TARGET_FILE

sed -i 's/<\/body>//g' $TARGET_FILE 
sed -i 's/<\/html>//g' $TARGET_FILE 

echo Line 1

if [ ! $(grep 'APPLICATION_NAME' $TARGET_FILE) ]; then

    echo "<div class='codedeploy'>">>$TARGET_FILE
    echo '<hr/>'>>$TARGET_FILE 
    echo "<h2>CodeDeploy Details</h2>">>$TARGET_FILE
    echo "<p>">>$TARGET_FILE
    echo "APPLICATION_NAME:$APPLICATION_NAME<br>">>$TARGET_FILE
    echo "DEPLOYMENT_ID:$DEPLOYMENT_ID<br>">>$TARGET_FILE
    echo "DEPLOYMENT_GROUP_NAME:$DEPLOYMENT_GROUP_NAME<br>">>$TARGET_FILE
    echo "DEPLOYMENT_GROUP_ID:$DEPLOYMENT_GROUP_ID<br>">>$TARGET_FILE
fi

echo "LIFECYCLE_EVENT:$LIFECYCLE_EVENT<br>">>$TARGET_FILE
    echo "</div>">>$TARGET_FILE
echo "</body>">>$TARGET_FILE
echo "</html>">>$TARGET_FILE
